#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AC_TimeHiding

#include "Basic.hpp"

#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AC_TimeHiding.AC_TimeHiding_C
// 0x0000 (0x00D8 - 0x00D8)
class UAC_TimeHiding_C final  : public UAIActionConsideration
{
public:
	float Score(struct FAIActionDecisionContext& Context, bool* bSuccess, class ACyberneticCharacter* CallFunc_GetCharacter_ReturnValue, float CallFunc_MapRangeClamped_ReturnValue) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AC_TimeHiding_C">();
	}
	static class UAC_TimeHiding_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAC_TimeHiding_C>();
	}
};
static_assert(alignof(UAC_TimeHiding_C) == 0x000008, "Wrong alignment on UAC_TimeHiding_C");
static_assert(sizeof(UAC_TimeHiding_C) == 0x0000D8, "Wrong size on UAC_TimeHiding_C");

}

