#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AG_TargetFacingMe

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "ReadyOrNot_structs.hpp"


namespace SDK::Params
{

// Function AG_TargetFacingMe.AG_TargetFacingMe_C.CanOpen
// 0x0090 (0x0090 - 0x0000)
struct AG_TargetFacingMe_C_CanOpen final 
{
public:
	struct FAIActionDecisionContext               Context;                                           // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)
	bool                                          ReturnValue;                                       // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4134[0x7];                                     // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AReadyOrNotCharacter*                   Target;                                            // 0x0018(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_DoesCharacterMatchTargetType_ReturnValue; // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4135[0x7];                                     // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AReadyOrNotCharacter*                   CallFunc_GetLastTrackedTarget_ReturnValue;         // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4136[0x7];                                     // 0x0031(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AReadyOrNotCharacter*                   CallFunc_GetTrackedTarget_ReturnValue;             // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ACyberneticCharacter*                   CallFunc_GetCharacter_ReturnValue;                 // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x0049(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4137[0x2];                                     // 0x004A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x004C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_1;        // 0x0058(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetActorForwardVector_ReturnValue;        // 0x0064(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Subtract_VectorVector_ReturnValue;        // 0x0070(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Vector_Normal2D_ReturnValue;              // 0x007C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Dot_VectorVector_ReturnValue;             // 0x0088(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue;           // 0x008C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_DoesCharacterMatchTargetType_ReturnValue_1; // 0x008D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(AG_TargetFacingMe_C_CanOpen) == 0x000008, "Wrong alignment on AG_TargetFacingMe_C_CanOpen");
static_assert(sizeof(AG_TargetFacingMe_C_CanOpen) == 0x000090, "Wrong size on AG_TargetFacingMe_C_CanOpen");
static_assert(offsetof(AG_TargetFacingMe_C_CanOpen, Context) == 0x000000, "Member 'AG_TargetFacingMe_C_CanOpen::Context' has a wrong offset!");
static_assert(offsetof(AG_TargetFacingMe_C_CanOpen, ReturnValue) == 0x000010, "Member 'AG_TargetFacingMe_C_CanOpen::ReturnValue' has a wrong offset!");
static_assert(offsetof(AG_TargetFacingMe_C_CanOpen, Target) == 0x000018, "Member 'AG_TargetFacingMe_C_CanOpen::Target' has a wrong offset!");
static_assert(offsetof(AG_TargetFacingMe_C_CanOpen, CallFunc_DoesCharacterMatchTargetType_ReturnValue) == 0x000020, "Member 'AG_TargetFacingMe_C_CanOpen::CallFunc_DoesCharacterMatchTargetType_ReturnValue' has a wrong offset!");
static_assert(offsetof(AG_TargetFacingMe_C_CanOpen, CallFunc_GetLastTrackedTarget_ReturnValue) == 0x000028, "Member 'AG_TargetFacingMe_C_CanOpen::CallFunc_GetLastTrackedTarget_ReturnValue' has a wrong offset!");
static_assert(offsetof(AG_TargetFacingMe_C_CanOpen, CallFunc_IsValid_ReturnValue) == 0x000030, "Member 'AG_TargetFacingMe_C_CanOpen::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(AG_TargetFacingMe_C_CanOpen, CallFunc_GetTrackedTarget_ReturnValue) == 0x000038, "Member 'AG_TargetFacingMe_C_CanOpen::CallFunc_GetTrackedTarget_ReturnValue' has a wrong offset!");
static_assert(offsetof(AG_TargetFacingMe_C_CanOpen, CallFunc_GetCharacter_ReturnValue) == 0x000040, "Member 'AG_TargetFacingMe_C_CanOpen::CallFunc_GetCharacter_ReturnValue' has a wrong offset!");
static_assert(offsetof(AG_TargetFacingMe_C_CanOpen, CallFunc_IsValid_ReturnValue_1) == 0x000048, "Member 'AG_TargetFacingMe_C_CanOpen::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(AG_TargetFacingMe_C_CanOpen, CallFunc_IsValid_ReturnValue_2) == 0x000049, "Member 'AG_TargetFacingMe_C_CanOpen::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(AG_TargetFacingMe_C_CanOpen, CallFunc_K2_GetActorLocation_ReturnValue) == 0x00004C, "Member 'AG_TargetFacingMe_C_CanOpen::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(AG_TargetFacingMe_C_CanOpen, CallFunc_K2_GetActorLocation_ReturnValue_1) == 0x000058, "Member 'AG_TargetFacingMe_C_CanOpen::CallFunc_K2_GetActorLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(AG_TargetFacingMe_C_CanOpen, CallFunc_GetActorForwardVector_ReturnValue) == 0x000064, "Member 'AG_TargetFacingMe_C_CanOpen::CallFunc_GetActorForwardVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(AG_TargetFacingMe_C_CanOpen, CallFunc_Subtract_VectorVector_ReturnValue) == 0x000070, "Member 'AG_TargetFacingMe_C_CanOpen::CallFunc_Subtract_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(AG_TargetFacingMe_C_CanOpen, CallFunc_Vector_Normal2D_ReturnValue) == 0x00007C, "Member 'AG_TargetFacingMe_C_CanOpen::CallFunc_Vector_Normal2D_ReturnValue' has a wrong offset!");
static_assert(offsetof(AG_TargetFacingMe_C_CanOpen, CallFunc_Dot_VectorVector_ReturnValue) == 0x000088, "Member 'AG_TargetFacingMe_C_CanOpen::CallFunc_Dot_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(AG_TargetFacingMe_C_CanOpen, CallFunc_Greater_FloatFloat_ReturnValue) == 0x00008C, "Member 'AG_TargetFacingMe_C_CanOpen::CallFunc_Greater_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(AG_TargetFacingMe_C_CanOpen, CallFunc_DoesCharacterMatchTargetType_ReturnValue_1) == 0x00008D, "Member 'AG_TargetFacingMe_C_CanOpen::CallFunc_DoesCharacterMatchTargetType_ReturnValue_1' has a wrong offset!");

}

