#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BaseBodyArmor

#include "Basic.hpp"

#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BaseBodyArmor.BaseBodyArmor_C
// 0x0000 (0x0A80 - 0x0A80)
class ABaseBodyArmor_C : public ASWATArmour
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BaseBodyArmor_C">();
	}
	static class ABaseBodyArmor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABaseBodyArmor_C>();
	}
};
static_assert(alignof(ABaseBodyArmor_C) == 0x000010, "Wrong alignment on ABaseBodyArmor_C");
static_assert(sizeof(ABaseBodyArmor_C) == 0x000A80, "Wrong size on ABaseBodyArmor_C");

}

