#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MessageDisplayBox

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BP_MessageDisplayBox.BP_MessageDisplayBox_C
// 0x0020 (0x02A8 - 0x0288)
class UBP_MessageDisplayBox_C final  : public UMessageDisplayBox
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0288(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UW_Button_C*                            Button_1;                                          // 0x0290(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       MessageText;                                       // 0x0298(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	bool                                          LastShowMouseCursor;                               // 0x02A0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          bDown;                                             // 0x02A1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          bHovering;                                         // 0x02A2(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_BP_MessageDisplayBox(int32 EntryPoint, class UW_Button_C* K2Node_ComponentBoundEvent_Button, bool CallFunc_StringIsEmpty_ReturnValue, class FText CallFunc_Conv_StringToText_ReturnValue, const struct FGeometry& K2Node_Event_MyGeometry, float K2Node_Event_InDeltaTime, class APlayerController* CallFunc_GetPlayerController_ReturnValue, class AReadyOrNotPlayerController* K2Node_DynamicCast_AsReady_or_Not_Player_Controller, bool K2Node_DynamicCast_bSuccess, class FText CallFunc_MakeLiteralText_ReturnValue, class APlayerController* CallFunc_GetPlayerController_ReturnValue_1, bool CallFunc_EqualEqual_TextText_ReturnValue, bool CallFunc_BooleanOR_ReturnValue);
	void BndEvt__BP_MessageDisplayBox_Button_1_K2Node_ComponentBoundEvent_0_Clicked__DelegateSignature(class UW_Button_C* Button);
	void Destruct();
	void Construct();
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);
	class FText Get_MessageTxt_Text_0(class FText CallFunc_Conv_StringToText_ReturnValue);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_MessageDisplayBox_C">();
	}
	static class UBP_MessageDisplayBox_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_MessageDisplayBox_C>();
	}
};
static_assert(alignof(UBP_MessageDisplayBox_C) == 0x000008, "Wrong alignment on UBP_MessageDisplayBox_C");
static_assert(sizeof(UBP_MessageDisplayBox_C) == 0x0002A8, "Wrong size on UBP_MessageDisplayBox_C");
static_assert(offsetof(UBP_MessageDisplayBox_C, UberGraphFrame) == 0x000288, "Member 'UBP_MessageDisplayBox_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UBP_MessageDisplayBox_C, Button_1) == 0x000290, "Member 'UBP_MessageDisplayBox_C::Button_1' has a wrong offset!");
static_assert(offsetof(UBP_MessageDisplayBox_C, MessageText) == 0x000298, "Member 'UBP_MessageDisplayBox_C::MessageText' has a wrong offset!");
static_assert(offsetof(UBP_MessageDisplayBox_C, LastShowMouseCursor) == 0x0002A0, "Member 'UBP_MessageDisplayBox_C::LastShowMouseCursor' has a wrong offset!");
static_assert(offsetof(UBP_MessageDisplayBox_C, bDown) == 0x0002A1, "Member 'UBP_MessageDisplayBox_C::bDown' has a wrong offset!");
static_assert(offsetof(UBP_MessageDisplayBox_C, bHovering) == 0x0002A2, "Member 'UBP_MessageDisplayBox_C::bHovering' has a wrong offset!");

}

