#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BulletImpactDebugText

#include "Basic.hpp"

#include "BulletImpactDebugText_classes.hpp"
#include "BulletImpactDebugText_parameters.hpp"


namespace SDK
{

// Function BulletImpactDebugText.BulletImpactDebugText_C.SetData
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Param_ID                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FText                             Param_Text                                             (BlueprintVisible, BlueprintReadOnly, Parm)

void UBulletImpactDebugText_C::SetData(int32 Param_ID, class FText Param_Text)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BulletImpactDebugText_C", "SetData");

	Params::BulletImpactDebugText_C_SetData Parms{};

	Parms.Param_ID = Param_ID;
	Parms.Param_Text = Param_Text;

	UObject::ProcessEvent(Func, &Parms);
}

}

