#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Cybernetics_Civilian_V2

#include "Basic.hpp"

#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Cybernetics_Civilian_V2.Cybernetics_Civilian_V2_C
// 0x0010 (0x1FA0 - 0x1F90)
class ACybernetics_Civilian_V2_C final  : public ACivilianCharacter
{
public:
	class FName                                   In_Bone_Name;                                      // 0x1F90(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Cybernetics_Civilian_V2_C">();
	}
	static class ACybernetics_Civilian_V2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACybernetics_Civilian_V2_C>();
	}
};
static_assert(alignof(ACybernetics_Civilian_V2_C) == 0x000010, "Wrong alignment on ACybernetics_Civilian_V2_C");
static_assert(sizeof(ACybernetics_Civilian_V2_C) == 0x001FA0, "Wrong size on ACybernetics_Civilian_V2_C");
static_assert(offsetof(ACybernetics_Civilian_V2_C, In_Bone_Name) == 0x001F90, "Member 'ACybernetics_Civilian_V2_C::In_Bone_Name' has a wrong offset!");

}

