#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Generic_Fire_M16A4

#include "Basic.hpp"

#include "GameplayCameras_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Generic_Fire_M16A4.Generic_Fire_M16A4_C
// 0x0000 (0x01B0 - 0x01B0)
class UGeneric_Fire_M16A4_C final  : public UMatineeCameraShake
{
public:
	void NewFunction_0();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Generic_Fire_M16A4_C">();
	}
	static class UGeneric_Fire_M16A4_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGeneric_Fire_M16A4_C>();
	}
};
static_assert(alignof(UGeneric_Fire_M16A4_C) == 0x000010, "Wrong alignment on UGeneric_Fire_M16A4_C");
static_assert(sizeof(UGeneric_Fire_M16A4_C) == 0x0001B0, "Wrong size on UGeneric_Fire_M16A4_C");

}

