#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Grenade_Roadflare

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function Grenade_Roadflare.Grenade_Roadflare_C.ExecuteUbergraph_Grenade_Roadflare
// 0x01C0 (0x01C0 - 0x0000)
struct Grenade_Roadflare_C_ExecuteUbergraph_Grenade_Roadflare final 
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class ABaseGrenade* Grenade)>  K2Node_CreateDelegate_OutputDelegate;              // 0x0004(0x0010)(ZeroConstructor, NoDestructor)
	float                                         K2Node_Event_DeltaSeconds;                         // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABaseGrenade*                           K2Node_CustomEvent_Grenade;                        // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x0020(0x0030)(IsPlainOldData, NoDestructor)
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue; // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue;      // 0x0058(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1682[0x4];                                     // 0x0064(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_LenFlare_RoadFlare_C*               CallFunc_FinishSpawningActor_ReturnValue;          // 0x0068(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue;             // 0x0070(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_K2_SetActorLocation_SweepHitResult;       // 0x007C(0x0088)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_K2_SetActorLocation_ReturnValue;          // 0x0104(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1683[0x3];                                     // 0x0105(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue_1;    // 0x0108(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue_1;           // 0x0114(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_K2_SetWorldLocation_SweepHitResult;       // 0x0120(0x0088)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	float                                         CallFunc_GetWorldDeltaSeconds_ReturnValue;         // 0x01A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_FInterpTo_ReturnValue;                    // 0x01AC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NearlyEqual_FloatFloat_ReturnValue;       // 0x01B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1684[0x3];                                     // 0x01B1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_MapRangeClamped_ReturnValue;              // 0x01B4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Grenade_Roadflare_C_ExecuteUbergraph_Grenade_Roadflare) == 0x000010, "Wrong alignment on Grenade_Roadflare_C_ExecuteUbergraph_Grenade_Roadflare");
static_assert(sizeof(Grenade_Roadflare_C_ExecuteUbergraph_Grenade_Roadflare) == 0x0001C0, "Wrong size on Grenade_Roadflare_C_ExecuteUbergraph_Grenade_Roadflare");
static_assert(offsetof(Grenade_Roadflare_C_ExecuteUbergraph_Grenade_Roadflare, EntryPoint) == 0x000000, "Member 'Grenade_Roadflare_C_ExecuteUbergraph_Grenade_Roadflare::EntryPoint' has a wrong offset!");
static_assert(offsetof(Grenade_Roadflare_C_ExecuteUbergraph_Grenade_Roadflare, K2Node_CreateDelegate_OutputDelegate) == 0x000004, "Member 'Grenade_Roadflare_C_ExecuteUbergraph_Grenade_Roadflare::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(Grenade_Roadflare_C_ExecuteUbergraph_Grenade_Roadflare, K2Node_Event_DeltaSeconds) == 0x000014, "Member 'Grenade_Roadflare_C_ExecuteUbergraph_Grenade_Roadflare::K2Node_Event_DeltaSeconds' has a wrong offset!");
static_assert(offsetof(Grenade_Roadflare_C_ExecuteUbergraph_Grenade_Roadflare, K2Node_CustomEvent_Grenade) == 0x000018, "Member 'Grenade_Roadflare_C_ExecuteUbergraph_Grenade_Roadflare::K2Node_CustomEvent_Grenade' has a wrong offset!");
static_assert(offsetof(Grenade_Roadflare_C_ExecuteUbergraph_Grenade_Roadflare, CallFunc_MakeTransform_ReturnValue) == 0x000020, "Member 'Grenade_Roadflare_C_ExecuteUbergraph_Grenade_Roadflare::CallFunc_MakeTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(Grenade_Roadflare_C_ExecuteUbergraph_Grenade_Roadflare, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue) == 0x000050, "Member 'Grenade_Roadflare_C_ExecuteUbergraph_Grenade_Roadflare::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(Grenade_Roadflare_C_ExecuteUbergraph_Grenade_Roadflare, CallFunc_K2_GetComponentLocation_ReturnValue) == 0x000058, "Member 'Grenade_Roadflare_C_ExecuteUbergraph_Grenade_Roadflare::CallFunc_K2_GetComponentLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(Grenade_Roadflare_C_ExecuteUbergraph_Grenade_Roadflare, CallFunc_FinishSpawningActor_ReturnValue) == 0x000068, "Member 'Grenade_Roadflare_C_ExecuteUbergraph_Grenade_Roadflare::CallFunc_FinishSpawningActor_ReturnValue' has a wrong offset!");
static_assert(offsetof(Grenade_Roadflare_C_ExecuteUbergraph_Grenade_Roadflare, CallFunc_Add_VectorVector_ReturnValue) == 0x000070, "Member 'Grenade_Roadflare_C_ExecuteUbergraph_Grenade_Roadflare::CallFunc_Add_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(Grenade_Roadflare_C_ExecuteUbergraph_Grenade_Roadflare, CallFunc_K2_SetActorLocation_SweepHitResult) == 0x00007C, "Member 'Grenade_Roadflare_C_ExecuteUbergraph_Grenade_Roadflare::CallFunc_K2_SetActorLocation_SweepHitResult' has a wrong offset!");
static_assert(offsetof(Grenade_Roadflare_C_ExecuteUbergraph_Grenade_Roadflare, CallFunc_K2_SetActorLocation_ReturnValue) == 0x000104, "Member 'Grenade_Roadflare_C_ExecuteUbergraph_Grenade_Roadflare::CallFunc_K2_SetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(Grenade_Roadflare_C_ExecuteUbergraph_Grenade_Roadflare, CallFunc_K2_GetComponentLocation_ReturnValue_1) == 0x000108, "Member 'Grenade_Roadflare_C_ExecuteUbergraph_Grenade_Roadflare::CallFunc_K2_GetComponentLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Grenade_Roadflare_C_ExecuteUbergraph_Grenade_Roadflare, CallFunc_Add_VectorVector_ReturnValue_1) == 0x000114, "Member 'Grenade_Roadflare_C_ExecuteUbergraph_Grenade_Roadflare::CallFunc_Add_VectorVector_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Grenade_Roadflare_C_ExecuteUbergraph_Grenade_Roadflare, CallFunc_K2_SetWorldLocation_SweepHitResult) == 0x000120, "Member 'Grenade_Roadflare_C_ExecuteUbergraph_Grenade_Roadflare::CallFunc_K2_SetWorldLocation_SweepHitResult' has a wrong offset!");
static_assert(offsetof(Grenade_Roadflare_C_ExecuteUbergraph_Grenade_Roadflare, CallFunc_GetWorldDeltaSeconds_ReturnValue) == 0x0001A8, "Member 'Grenade_Roadflare_C_ExecuteUbergraph_Grenade_Roadflare::CallFunc_GetWorldDeltaSeconds_ReturnValue' has a wrong offset!");
static_assert(offsetof(Grenade_Roadflare_C_ExecuteUbergraph_Grenade_Roadflare, CallFunc_FInterpTo_ReturnValue) == 0x0001AC, "Member 'Grenade_Roadflare_C_ExecuteUbergraph_Grenade_Roadflare::CallFunc_FInterpTo_ReturnValue' has a wrong offset!");
static_assert(offsetof(Grenade_Roadflare_C_ExecuteUbergraph_Grenade_Roadflare, CallFunc_NearlyEqual_FloatFloat_ReturnValue) == 0x0001B0, "Member 'Grenade_Roadflare_C_ExecuteUbergraph_Grenade_Roadflare::CallFunc_NearlyEqual_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(Grenade_Roadflare_C_ExecuteUbergraph_Grenade_Roadflare, CallFunc_MapRangeClamped_ReturnValue) == 0x0001B4, "Member 'Grenade_Roadflare_C_ExecuteUbergraph_Grenade_Roadflare::CallFunc_MapRangeClamped_ReturnValue' has a wrong offset!");

// Function Grenade_Roadflare.Grenade_Roadflare_C.DetonateBind
// 0x0008 (0x0008 - 0x0000)
struct Grenade_Roadflare_C_DetonateBind final 
{
public:
	class ABaseGrenade*                           Grenade;                                           // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Grenade_Roadflare_C_DetonateBind) == 0x000008, "Wrong alignment on Grenade_Roadflare_C_DetonateBind");
static_assert(sizeof(Grenade_Roadflare_C_DetonateBind) == 0x000008, "Wrong size on Grenade_Roadflare_C_DetonateBind");
static_assert(offsetof(Grenade_Roadflare_C_DetonateBind, Grenade) == 0x000000, "Member 'Grenade_Roadflare_C_DetonateBind::Grenade' has a wrong offset!");

// Function Grenade_Roadflare.Grenade_Roadflare_C.ReceiveTick
// 0x0004 (0x0004 - 0x0000)
struct Grenade_Roadflare_C_ReceiveTick final 
{
public:
	float                                         DeltaSeconds;                                      // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Grenade_Roadflare_C_ReceiveTick) == 0x000004, "Wrong alignment on Grenade_Roadflare_C_ReceiveTick");
static_assert(sizeof(Grenade_Roadflare_C_ReceiveTick) == 0x000004, "Wrong size on Grenade_Roadflare_C_ReceiveTick");
static_assert(offsetof(Grenade_Roadflare_C_ReceiveTick, DeltaSeconds) == 0x000000, "Member 'Grenade_Roadflare_C_ReceiveTick::DeltaSeconds' has a wrong offset!");

}

