#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Helmet_NVG_V2

#include "Basic.hpp"


namespace SDK::Params
{

// Function Helmet_NVG_V2.Helmet_NVG_V2_C.ExecuteUbergraph_Helmet_NVG_V2
// 0x0008 (0x0008 - 0x0000)
struct Helmet_NVG_V2_C_ExecuteUbergraph_Helmet_NVG_V2 final 
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_DeltaSeconds;                         // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Helmet_NVG_V2_C_ExecuteUbergraph_Helmet_NVG_V2) == 0x000004, "Wrong alignment on Helmet_NVG_V2_C_ExecuteUbergraph_Helmet_NVG_V2");
static_assert(sizeof(Helmet_NVG_V2_C_ExecuteUbergraph_Helmet_NVG_V2) == 0x000008, "Wrong size on Helmet_NVG_V2_C_ExecuteUbergraph_Helmet_NVG_V2");
static_assert(offsetof(Helmet_NVG_V2_C_ExecuteUbergraph_Helmet_NVG_V2, EntryPoint) == 0x000000, "Member 'Helmet_NVG_V2_C_ExecuteUbergraph_Helmet_NVG_V2::EntryPoint' has a wrong offset!");
static_assert(offsetof(Helmet_NVG_V2_C_ExecuteUbergraph_Helmet_NVG_V2, K2Node_Event_DeltaSeconds) == 0x000004, "Member 'Helmet_NVG_V2_C_ExecuteUbergraph_Helmet_NVG_V2::K2Node_Event_DeltaSeconds' has a wrong offset!");

// Function Helmet_NVG_V2.Helmet_NVG_V2_C.ReceiveTick
// 0x0004 (0x0004 - 0x0000)
struct Helmet_NVG_V2_C_ReceiveTick final 
{
public:
	float                                         DeltaSeconds;                                      // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Helmet_NVG_V2_C_ReceiveTick) == 0x000004, "Wrong alignment on Helmet_NVG_V2_C_ReceiveTick");
static_assert(sizeof(Helmet_NVG_V2_C_ReceiveTick) == 0x000004, "Wrong size on Helmet_NVG_V2_C_ReceiveTick");
static_assert(offsetof(Helmet_NVG_V2_C_ReceiveTick, DeltaSeconds) == 0x000000, "Member 'Helmet_NVG_V2_C_ReceiveTick::DeltaSeconds' has a wrong offset!");

}

