#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: InviteButtonStyle1

#include "Basic.hpp"

#include "BaseButtonStyle_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass InviteButtonStyle1.InviteButtonStyle1_C
// 0x0000 (0x0598 - 0x0598)
class UInviteButtonStyle1_C final  : public UBaseButtonStyle_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"InviteButtonStyle1_C">();
	}
	static class UInviteButtonStyle1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UInviteButtonStyle1_C>();
	}
};
static_assert(alignof(UInviteButtonStyle1_C) == 0x000008, "Wrong alignment on UInviteButtonStyle1_C");
static_assert(sizeof(UInviteButtonStyle1_C) == 0x000598, "Wrong size on UInviteButtonStyle1_C");

}

