#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ModioModTileWidget

#include "Basic.hpp"

#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function ModioModTileWidget.ModioModTileWidget_C.ExecuteUbergraph_ModioModTileWidget
// 0x0040 (0x0040 - 0x0000)
struct ModioModTileWidget_C_ExecuteUbergraph_ModioModTileWidget final 
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGeometry                              K2Node_Event_MyGeometry;                           // 0x0004(0x0038)(IsPlainOldData, NoDestructor)
	float                                         K2Node_Event_InDeltaTime;                          // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ModioModTileWidget_C_ExecuteUbergraph_ModioModTileWidget) == 0x000004, "Wrong alignment on ModioModTileWidget_C_ExecuteUbergraph_ModioModTileWidget");
static_assert(sizeof(ModioModTileWidget_C_ExecuteUbergraph_ModioModTileWidget) == 0x000040, "Wrong size on ModioModTileWidget_C_ExecuteUbergraph_ModioModTileWidget");
static_assert(offsetof(ModioModTileWidget_C_ExecuteUbergraph_ModioModTileWidget, EntryPoint) == 0x000000, "Member 'ModioModTileWidget_C_ExecuteUbergraph_ModioModTileWidget::EntryPoint' has a wrong offset!");
static_assert(offsetof(ModioModTileWidget_C_ExecuteUbergraph_ModioModTileWidget, K2Node_Event_MyGeometry) == 0x000004, "Member 'ModioModTileWidget_C_ExecuteUbergraph_ModioModTileWidget::K2Node_Event_MyGeometry' has a wrong offset!");
static_assert(offsetof(ModioModTileWidget_C_ExecuteUbergraph_ModioModTileWidget, K2Node_Event_InDeltaTime) == 0x00003C, "Member 'ModioModTileWidget_C_ExecuteUbergraph_ModioModTileWidget::K2Node_Event_InDeltaTime' has a wrong offset!");

// Function ModioModTileWidget.ModioModTileWidget_C.Tick
// 0x003C (0x003C - 0x0000)
struct ModioModTileWidget_C_Tick final 
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	float                                         InDeltaTime;                                       // 0x0038(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ModioModTileWidget_C_Tick) == 0x000004, "Wrong alignment on ModioModTileWidget_C_Tick");
static_assert(sizeof(ModioModTileWidget_C_Tick) == 0x00003C, "Wrong size on ModioModTileWidget_C_Tick");
static_assert(offsetof(ModioModTileWidget_C_Tick, MyGeometry) == 0x000000, "Member 'ModioModTileWidget_C_Tick::MyGeometry' has a wrong offset!");
static_assert(offsetof(ModioModTileWidget_C_Tick, InDeltaTime) == 0x000038, "Member 'ModioModTileWidget_C_Tick::InDeltaTime' has a wrong offset!");

}

