#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PepperballImpactEffects

#include "Basic.hpp"

#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PepperballImpactEffects.PepperballImpactEffects_C
// 0x0000 (0x0D98 - 0x0D98)
class APepperballImpactEffects_C final  : public AImpactEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PepperballImpactEffects_C">();
	}
	static class APepperballImpactEffects_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APepperballImpactEffects_C>();
	}
};
static_assert(alignof(APepperballImpactEffects_C) == 0x000008, "Wrong alignment on APepperballImpactEffects_C");
static_assert(sizeof(APepperballImpactEffects_C) == 0x000D98, "Wrong size on APepperballImpactEffects_C");

}

