#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Rifle_AFG_MLOK

#include "Basic.hpp"

#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Rifle_AFG_MLOK.Rifle_AFG_MLOK_C
// 0x0000 (0x1000 - 0x1000)
class URifle_AFG_MLOK_C final  : public UWeaponAttachment
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Rifle_AFG_MLOK_C">();
	}
	static class URifle_AFG_MLOK_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<URifle_AFG_MLOK_C>();
	}
};
static_assert(alignof(URifle_AFG_MLOK_C) == 0x000010, "Wrong alignment on URifle_AFG_MLOK_C");
static_assert(sizeof(URifle_AFG_MLOK_C) == 0x001000, "Wrong size on URifle_AFG_MLOK_C");

}

