#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SimpleButtonSelectedTextStyle

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SimpleButtonSelectedTextStyle.SimpleButtonSelectedTextStyle_C
// 0x0000 (0x0150 - 0x0150)
class USimpleButtonSelectedTextStyle_C final  : public UCommonTextStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SimpleButtonSelectedTextStyle_C">();
	}
	static class USimpleButtonSelectedTextStyle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USimpleButtonSelectedTextStyle_C>();
	}
};
static_assert(alignof(USimpleButtonSelectedTextStyle_C) == 0x000008, "Wrong alignment on USimpleButtonSelectedTextStyle_C");
static_assert(sizeof(USimpleButtonSelectedTextStyle_C) == 0x000150, "Wrong size on USimpleButtonSelectedTextStyle_C");

}

