#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_DebugInfo

#include "Basic.hpp"

#include "W_DebugInfo_classes.hpp"
#include "W_DebugInfo_parameters.hpp"


namespace SDK
{

// Function W_DebugInfo.W_DebugInfo_C.ExecuteUbergraph_W_DebugInfo
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    K2Node_Event_IsDesignTime                              (ZeroConstructor, IsPlainOldData, NoDestructor)

void UW_DebugInfo_C::ExecuteUbergraph_W_DebugInfo(int32 EntryPoint, bool K2Node_Event_IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_DebugInfo_C", "ExecuteUbergraph_W_DebugInfo");

	Params::W_DebugInfo_C_ExecuteUbergraph_W_DebugInfo Parms{};

	Parms.EntryPoint = EntryPoint;
	Parms.K2Node_Event_IsDesignTime = K2Node_Event_IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_DebugInfo.W_DebugInfo_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UW_DebugInfo_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_DebugInfo_C", "PreConstruct");

	Params::W_DebugInfo_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_DebugInfo.W_DebugInfo_C.SetDebugValue
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             DebugText                                              (BlueprintVisible, BlueprintReadOnly, Parm)

void UW_DebugInfo_C::SetDebugValue(class FText DebugText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_DebugInfo_C", "SetDebugValue");

	Params::W_DebugInfo_C_SetDebugValue Parms{};

	Parms.DebugText = DebugText;

	UObject::ProcessEvent(Func, &Parms);
}

}

