#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_ItemSelection_ItemGroupList_V2

#include "Basic.hpp"

#include "ReadyOrNot_structs.hpp"
#include "SlateCore_structs.hpp"
#include "FMODStudio_structs.hpp"
#include "UMG_structs.hpp"


namespace SDK::Params
{

// Function W_ItemSelection_ItemGroupList_V2.W_ItemSelection_ItemGroupList_V2_C.Initialize
// 0x00C0 (0x00C0 - 0x0000)
struct W_ItemSelection_ItemGroupList_V2_C_Initialize final 
{
public:
	TArray<struct FItemSelectionGroup>            InItemGroupArray;                                  // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	TArray<class ABaseItem*>                      Items;                                             // 0x0010(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_LastIndex_ReturnValue;              // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FItemSelectionGroup                    CallFunc_Array_Get_Item;                           // 0x0030(0x0048)()
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3BE0[0x3];                                     // 0x0079(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x007C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3BE1[0x3];                                     // 0x0081(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FMargin                                K2Node_MakeStruct_Margin;                          // 0x0084(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3BE2[0x4];                                     // 0x0094(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x0098(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateChildSize                        K2Node_MakeStruct_SlateChildSize;                  // 0x00A0(0x0008)(NoDestructor)
	class UW_ItemSelection_ItemList_V2_C*         CallFunc_Create_ReturnValue;                       // 0x00A8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x00B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3BE3[0x4];                                     // 0x00B4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UHorizontalBoxSlot*                     CallFunc_AddChildToHorizontalBox_ReturnValue;      // 0x00B8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_ItemSelection_ItemGroupList_V2_C_Initialize) == 0x000008, "Wrong alignment on W_ItemSelection_ItemGroupList_V2_C_Initialize");
static_assert(sizeof(W_ItemSelection_ItemGroupList_V2_C_Initialize) == 0x0000C0, "Wrong size on W_ItemSelection_ItemGroupList_V2_C_Initialize");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_Initialize, InItemGroupArray) == 0x000000, "Member 'W_ItemSelection_ItemGroupList_V2_C_Initialize::InItemGroupArray' has a wrong offset!");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_Initialize, Items) == 0x000010, "Member 'W_ItemSelection_ItemGroupList_V2_C_Initialize::Items' has a wrong offset!");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_Initialize, CallFunc_Array_Length_ReturnValue) == 0x000020, "Member 'W_ItemSelection_ItemGroupList_V2_C_Initialize::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_Initialize, CallFunc_Array_LastIndex_ReturnValue) == 0x000024, "Member 'W_ItemSelection_ItemGroupList_V2_C_Initialize::CallFunc_Array_LastIndex_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_Initialize, Temp_int_Array_Index_Variable) == 0x000028, "Member 'W_ItemSelection_ItemGroupList_V2_C_Initialize::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_Initialize, Temp_int_Loop_Counter_Variable) == 0x00002C, "Member 'W_ItemSelection_ItemGroupList_V2_C_Initialize::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_Initialize, CallFunc_Array_Get_Item) == 0x000030, "Member 'W_ItemSelection_ItemGroupList_V2_C_Initialize::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_Initialize, CallFunc_Less_IntInt_ReturnValue) == 0x000078, "Member 'W_ItemSelection_ItemGroupList_V2_C_Initialize::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_Initialize, CallFunc_Add_IntInt_ReturnValue) == 0x00007C, "Member 'W_ItemSelection_ItemGroupList_V2_C_Initialize::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_Initialize, CallFunc_EqualEqual_IntInt_ReturnValue) == 0x000080, "Member 'W_ItemSelection_ItemGroupList_V2_C_Initialize::CallFunc_EqualEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_Initialize, K2Node_MakeStruct_Margin) == 0x000084, "Member 'W_ItemSelection_ItemGroupList_V2_C_Initialize::K2Node_MakeStruct_Margin' has a wrong offset!");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_Initialize, CallFunc_GetOwningPlayer_ReturnValue) == 0x000098, "Member 'W_ItemSelection_ItemGroupList_V2_C_Initialize::CallFunc_GetOwningPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_Initialize, K2Node_MakeStruct_SlateChildSize) == 0x0000A0, "Member 'W_ItemSelection_ItemGroupList_V2_C_Initialize::K2Node_MakeStruct_SlateChildSize' has a wrong offset!");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_Initialize, CallFunc_Create_ReturnValue) == 0x0000A8, "Member 'W_ItemSelection_ItemGroupList_V2_C_Initialize::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_Initialize, CallFunc_Array_Add_ReturnValue) == 0x0000B0, "Member 'W_ItemSelection_ItemGroupList_V2_C_Initialize::CallFunc_Array_Add_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_Initialize, CallFunc_AddChildToHorizontalBox_ReturnValue) == 0x0000B8, "Member 'W_ItemSelection_ItemGroupList_V2_C_Initialize::CallFunc_AddChildToHorizontalBox_ReturnValue' has a wrong offset!");

// Function W_ItemSelection_ItemGroupList_V2.W_ItemSelection_ItemGroupList_V2_C.SelectList
// 0x0030 (0x0030 - 0x0000)
struct W_ItemSelection_ItemGroupList_V2_C_SelectList final 
{
public:
	int32                                         Param_Index;                                       // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_IntInt_ReturnValue;              // 0x000C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3BE4[0x3];                                     // 0x000D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3BE5[0x4];                                     // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UW_ItemSelection_ItemList_V2_C*         CallFunc_Array_Get_Item;                           // 0x0018(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UW_ItemSelection_ItemList_V2_C*         CallFunc_Array_Get_Item_1;                         // 0x0020(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x002C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(W_ItemSelection_ItemGroupList_V2_C_SelectList) == 0x000008, "Wrong alignment on W_ItemSelection_ItemGroupList_V2_C_SelectList");
static_assert(sizeof(W_ItemSelection_ItemGroupList_V2_C_SelectList) == 0x000030, "Wrong size on W_ItemSelection_ItemGroupList_V2_C_SelectList");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_SelectList, Param_Index) == 0x000000, "Member 'W_ItemSelection_ItemGroupList_V2_C_SelectList::Param_Index' has a wrong offset!");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_SelectList, Temp_int_Array_Index_Variable) == 0x000004, "Member 'W_ItemSelection_ItemGroupList_V2_C_SelectList::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_SelectList, Temp_int_Loop_Counter_Variable) == 0x000008, "Member 'W_ItemSelection_ItemGroupList_V2_C_SelectList::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_SelectList, CallFunc_NotEqual_IntInt_ReturnValue) == 0x00000C, "Member 'W_ItemSelection_ItemGroupList_V2_C_SelectList::CallFunc_NotEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_SelectList, CallFunc_Add_IntInt_ReturnValue) == 0x000010, "Member 'W_ItemSelection_ItemGroupList_V2_C_SelectList::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_SelectList, CallFunc_Array_Get_Item) == 0x000018, "Member 'W_ItemSelection_ItemGroupList_V2_C_SelectList::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_SelectList, CallFunc_Array_Get_Item_1) == 0x000020, "Member 'W_ItemSelection_ItemGroupList_V2_C_SelectList::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_SelectList, CallFunc_Array_Length_ReturnValue) == 0x000028, "Member 'W_ItemSelection_ItemGroupList_V2_C_SelectList::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_SelectList, CallFunc_Less_IntInt_ReturnValue) == 0x00002C, "Member 'W_ItemSelection_ItemGroupList_V2_C_SelectList::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");

// Function W_ItemSelection_ItemGroupList_V2.W_ItemSelection_ItemGroupList_V2_C.SelectCategory
// 0x0018 (0x0018 - 0x0000)
struct W_ItemSelection_ItemGroupList_V2_C_SelectCategory final 
{
public:
	int32                                         GroupIndex;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CategoryIndex;                                     // 0x0004(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FFMODEventInstance                     CallFunc_PlayEvent2D_ReturnValue;                  // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class UW_ItemSelection_ItemList_V2_C*         CallFunc_Array_Get_Item;                           // 0x0010(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_ItemSelection_ItemGroupList_V2_C_SelectCategory) == 0x000008, "Wrong alignment on W_ItemSelection_ItemGroupList_V2_C_SelectCategory");
static_assert(sizeof(W_ItemSelection_ItemGroupList_V2_C_SelectCategory) == 0x000018, "Wrong size on W_ItemSelection_ItemGroupList_V2_C_SelectCategory");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_SelectCategory, GroupIndex) == 0x000000, "Member 'W_ItemSelection_ItemGroupList_V2_C_SelectCategory::GroupIndex' has a wrong offset!");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_SelectCategory, CategoryIndex) == 0x000004, "Member 'W_ItemSelection_ItemGroupList_V2_C_SelectCategory::CategoryIndex' has a wrong offset!");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_SelectCategory, CallFunc_PlayEvent2D_ReturnValue) == 0x000008, "Member 'W_ItemSelection_ItemGroupList_V2_C_SelectCategory::CallFunc_PlayEvent2D_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_SelectCategory, CallFunc_Array_Get_Item) == 0x000010, "Member 'W_ItemSelection_ItemGroupList_V2_C_SelectCategory::CallFunc_Array_Get_Item' has a wrong offset!");

// Function W_ItemSelection_ItemGroupList_V2.W_ItemSelection_ItemGroupList_V2_C.UpdateKeybinds
// 0x0030 (0x0030 - 0x0000)
struct W_ItemSelection_ItemGroupList_V2_C_UpdateKeybinds final 
{
public:
	TArray<struct FItemSelectionGroup>            InItemGroups;                                      // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UW_ItemSelection_ItemList_V2_C*         CallFunc_Array_Get_Item;                           // 0x0020(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(W_ItemSelection_ItemGroupList_V2_C_UpdateKeybinds) == 0x000008, "Wrong alignment on W_ItemSelection_ItemGroupList_V2_C_UpdateKeybinds");
static_assert(sizeof(W_ItemSelection_ItemGroupList_V2_C_UpdateKeybinds) == 0x000030, "Wrong size on W_ItemSelection_ItemGroupList_V2_C_UpdateKeybinds");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_UpdateKeybinds, InItemGroups) == 0x000000, "Member 'W_ItemSelection_ItemGroupList_V2_C_UpdateKeybinds::InItemGroups' has a wrong offset!");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_UpdateKeybinds, Temp_int_Array_Index_Variable) == 0x000010, "Member 'W_ItemSelection_ItemGroupList_V2_C_UpdateKeybinds::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_UpdateKeybinds, Temp_int_Loop_Counter_Variable) == 0x000014, "Member 'W_ItemSelection_ItemGroupList_V2_C_UpdateKeybinds::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_UpdateKeybinds, CallFunc_Add_IntInt_ReturnValue) == 0x000018, "Member 'W_ItemSelection_ItemGroupList_V2_C_UpdateKeybinds::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_UpdateKeybinds, CallFunc_Array_Length_ReturnValue) == 0x00001C, "Member 'W_ItemSelection_ItemGroupList_V2_C_UpdateKeybinds::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_UpdateKeybinds, CallFunc_Array_Get_Item) == 0x000020, "Member 'W_ItemSelection_ItemGroupList_V2_C_UpdateKeybinds::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_UpdateKeybinds, CallFunc_Less_IntInt_ReturnValue) == 0x000028, "Member 'W_ItemSelection_ItemGroupList_V2_C_UpdateKeybinds::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");

// Function W_ItemSelection_ItemGroupList_V2.W_ItemSelection_ItemGroupList_V2_C.FadeOutAllExcept
// 0x0030 (0x0030 - 0x0000)
struct W_ItemSelection_ItemGroupList_V2_C_FadeOutAllExcept final 
{
public:
	int32                                         Param_Index;                                       // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x000C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3BE6[0x3];                                     // 0x000D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_IntInt_ReturnValue;              // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3BE7[0x3];                                     // 0x0015(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3BE8[0x4];                                     // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UW_ItemSelection_ItemList_V2_C*         CallFunc_Array_Get_Item;                           // 0x0020(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(W_ItemSelection_ItemGroupList_V2_C_FadeOutAllExcept) == 0x000008, "Wrong alignment on W_ItemSelection_ItemGroupList_V2_C_FadeOutAllExcept");
static_assert(sizeof(W_ItemSelection_ItemGroupList_V2_C_FadeOutAllExcept) == 0x000030, "Wrong size on W_ItemSelection_ItemGroupList_V2_C_FadeOutAllExcept");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_FadeOutAllExcept, Param_Index) == 0x000000, "Member 'W_ItemSelection_ItemGroupList_V2_C_FadeOutAllExcept::Param_Index' has a wrong offset!");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_FadeOutAllExcept, Temp_int_Array_Index_Variable) == 0x000004, "Member 'W_ItemSelection_ItemGroupList_V2_C_FadeOutAllExcept::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_FadeOutAllExcept, Temp_int_Loop_Counter_Variable) == 0x000008, "Member 'W_ItemSelection_ItemGroupList_V2_C_FadeOutAllExcept::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_FadeOutAllExcept, CallFunc_EqualEqual_IntInt_ReturnValue) == 0x00000C, "Member 'W_ItemSelection_ItemGroupList_V2_C_FadeOutAllExcept::CallFunc_EqualEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_FadeOutAllExcept, CallFunc_Add_IntInt_ReturnValue) == 0x000010, "Member 'W_ItemSelection_ItemGroupList_V2_C_FadeOutAllExcept::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_FadeOutAllExcept, CallFunc_NotEqual_IntInt_ReturnValue) == 0x000014, "Member 'W_ItemSelection_ItemGroupList_V2_C_FadeOutAllExcept::CallFunc_NotEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_FadeOutAllExcept, CallFunc_Array_Length_ReturnValue) == 0x000018, "Member 'W_ItemSelection_ItemGroupList_V2_C_FadeOutAllExcept::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_FadeOutAllExcept, CallFunc_Array_Get_Item) == 0x000020, "Member 'W_ItemSelection_ItemGroupList_V2_C_FadeOutAllExcept::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_FadeOutAllExcept, CallFunc_Less_IntInt_ReturnValue) == 0x000028, "Member 'W_ItemSelection_ItemGroupList_V2_C_FadeOutAllExcept::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");

// Function W_ItemSelection_ItemGroupList_V2.W_ItemSelection_ItemGroupList_V2_C.ResetAnimationState
// 0x0020 (0x0020 - 0x0000)
struct W_ItemSelection_ItemGroupList_V2_C_ResetAnimationState final 
{
public:
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UW_ItemSelection_ItemList_V2_C*         CallFunc_Array_Get_Item;                           // 0x0010(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(W_ItemSelection_ItemGroupList_V2_C_ResetAnimationState) == 0x000008, "Wrong alignment on W_ItemSelection_ItemGroupList_V2_C_ResetAnimationState");
static_assert(sizeof(W_ItemSelection_ItemGroupList_V2_C_ResetAnimationState) == 0x000020, "Wrong size on W_ItemSelection_ItemGroupList_V2_C_ResetAnimationState");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_ResetAnimationState, Temp_int_Array_Index_Variable) == 0x000000, "Member 'W_ItemSelection_ItemGroupList_V2_C_ResetAnimationState::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_ResetAnimationState, Temp_int_Loop_Counter_Variable) == 0x000004, "Member 'W_ItemSelection_ItemGroupList_V2_C_ResetAnimationState::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_ResetAnimationState, CallFunc_Add_IntInt_ReturnValue) == 0x000008, "Member 'W_ItemSelection_ItemGroupList_V2_C_ResetAnimationState::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_ResetAnimationState, CallFunc_Array_Length_ReturnValue) == 0x00000C, "Member 'W_ItemSelection_ItemGroupList_V2_C_ResetAnimationState::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_ResetAnimationState, CallFunc_Array_Get_Item) == 0x000010, "Member 'W_ItemSelection_ItemGroupList_V2_C_ResetAnimationState::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_ResetAnimationState, CallFunc_Less_IntInt_ReturnValue) == 0x000018, "Member 'W_ItemSelection_ItemGroupList_V2_C_ResetAnimationState::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");

// Function W_ItemSelection_ItemGroupList_V2.W_ItemSelection_ItemGroupList_V2_C.Get List At Index
// 0x0020 (0x0020 - 0x0000)
struct W_ItemSelection_ItemGroupList_V2_C_Get_List_At_Index final 
{
public:
	int32                                         Param_Index;                                       // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3BE9[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UW_ItemSelection_ItemList_V2_C*         Return_Value;                                      // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_IsValidIndex_ReturnValue;           // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3BEA[0x7];                                     // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UW_ItemSelection_ItemList_V2_C*         CallFunc_Array_Get_Item;                           // 0x0018(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_ItemSelection_ItemGroupList_V2_C_Get_List_At_Index) == 0x000008, "Wrong alignment on W_ItemSelection_ItemGroupList_V2_C_Get_List_At_Index");
static_assert(sizeof(W_ItemSelection_ItemGroupList_V2_C_Get_List_At_Index) == 0x000020, "Wrong size on W_ItemSelection_ItemGroupList_V2_C_Get_List_At_Index");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_Get_List_At_Index, Param_Index) == 0x000000, "Member 'W_ItemSelection_ItemGroupList_V2_C_Get_List_At_Index::Param_Index' has a wrong offset!");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_Get_List_At_Index, Return_Value) == 0x000008, "Member 'W_ItemSelection_ItemGroupList_V2_C_Get_List_At_Index::Return_Value' has a wrong offset!");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_Get_List_At_Index, CallFunc_Array_IsValidIndex_ReturnValue) == 0x000010, "Member 'W_ItemSelection_ItemGroupList_V2_C_Get_List_At_Index::CallFunc_Array_IsValidIndex_ReturnValue' has a wrong offset!");
static_assert(offsetof(W_ItemSelection_ItemGroupList_V2_C_Get_List_At_Index, CallFunc_Array_Get_Item) == 0x000018, "Member 'W_ItemSelection_ItemGroupList_V2_C_Get_List_At_Index::CallFunc_Array_Get_Item' has a wrong offset!");

}

