#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_MainMenu_SubButton_V3

#include "Basic.hpp"

#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function W_MainMenu_SubButton_V3.W_MainMenu_SubButton_V3_C.ExecuteUbergraph_W_MainMenu_SubButton_V3
// 0x0018 (0x0018 - 0x0000)
struct W_MainMenu_SubButton_V3_C_ExecuteUbergraph_W_MainMenu_SubButton_V3 final 
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_41F9[0x3];                                     // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFocusEvent                            K2Node_Event_InFocusEvent_1;                       // 0x0008(0x0008)(NoDestructor)
	struct FFocusEvent                            K2Node_Event_InFocusEvent;                         // 0x0010(0x0008)(NoDestructor)
};
static_assert(alignof(W_MainMenu_SubButton_V3_C_ExecuteUbergraph_W_MainMenu_SubButton_V3) == 0x000004, "Wrong alignment on W_MainMenu_SubButton_V3_C_ExecuteUbergraph_W_MainMenu_SubButton_V3");
static_assert(sizeof(W_MainMenu_SubButton_V3_C_ExecuteUbergraph_W_MainMenu_SubButton_V3) == 0x000018, "Wrong size on W_MainMenu_SubButton_V3_C_ExecuteUbergraph_W_MainMenu_SubButton_V3");
static_assert(offsetof(W_MainMenu_SubButton_V3_C_ExecuteUbergraph_W_MainMenu_SubButton_V3, EntryPoint) == 0x000000, "Member 'W_MainMenu_SubButton_V3_C_ExecuteUbergraph_W_MainMenu_SubButton_V3::EntryPoint' has a wrong offset!");
static_assert(offsetof(W_MainMenu_SubButton_V3_C_ExecuteUbergraph_W_MainMenu_SubButton_V3, K2Node_Event_IsDesignTime) == 0x000004, "Member 'W_MainMenu_SubButton_V3_C_ExecuteUbergraph_W_MainMenu_SubButton_V3::K2Node_Event_IsDesignTime' has a wrong offset!");
static_assert(offsetof(W_MainMenu_SubButton_V3_C_ExecuteUbergraph_W_MainMenu_SubButton_V3, K2Node_Event_InFocusEvent_1) == 0x000008, "Member 'W_MainMenu_SubButton_V3_C_ExecuteUbergraph_W_MainMenu_SubButton_V3::K2Node_Event_InFocusEvent_1' has a wrong offset!");
static_assert(offsetof(W_MainMenu_SubButton_V3_C_ExecuteUbergraph_W_MainMenu_SubButton_V3, K2Node_Event_InFocusEvent) == 0x000010, "Member 'W_MainMenu_SubButton_V3_C_ExecuteUbergraph_W_MainMenu_SubButton_V3::K2Node_Event_InFocusEvent' has a wrong offset!");

// Function W_MainMenu_SubButton_V3.W_MainMenu_SubButton_V3_C.OnRemovedFromFocusPath
// 0x0008 (0x0008 - 0x0000)
struct W_MainMenu_SubButton_V3_C_OnRemovedFromFocusPath final 
{
public:
	struct FFocusEvent                            InFocusEvent;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
};
static_assert(alignof(W_MainMenu_SubButton_V3_C_OnRemovedFromFocusPath) == 0x000004, "Wrong alignment on W_MainMenu_SubButton_V3_C_OnRemovedFromFocusPath");
static_assert(sizeof(W_MainMenu_SubButton_V3_C_OnRemovedFromFocusPath) == 0x000008, "Wrong size on W_MainMenu_SubButton_V3_C_OnRemovedFromFocusPath");
static_assert(offsetof(W_MainMenu_SubButton_V3_C_OnRemovedFromFocusPath, InFocusEvent) == 0x000000, "Member 'W_MainMenu_SubButton_V3_C_OnRemovedFromFocusPath::InFocusEvent' has a wrong offset!");

// Function W_MainMenu_SubButton_V3.W_MainMenu_SubButton_V3_C.OnAddedToFocusPath
// 0x0008 (0x0008 - 0x0000)
struct W_MainMenu_SubButton_V3_C_OnAddedToFocusPath final 
{
public:
	struct FFocusEvent                            InFocusEvent;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
};
static_assert(alignof(W_MainMenu_SubButton_V3_C_OnAddedToFocusPath) == 0x000004, "Wrong alignment on W_MainMenu_SubButton_V3_C_OnAddedToFocusPath");
static_assert(sizeof(W_MainMenu_SubButton_V3_C_OnAddedToFocusPath) == 0x000008, "Wrong size on W_MainMenu_SubButton_V3_C_OnAddedToFocusPath");
static_assert(offsetof(W_MainMenu_SubButton_V3_C_OnAddedToFocusPath, InFocusEvent) == 0x000000, "Member 'W_MainMenu_SubButton_V3_C_OnAddedToFocusPath::InFocusEvent' has a wrong offset!");

// Function W_MainMenu_SubButton_V3.W_MainMenu_SubButton_V3_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct W_MainMenu_SubButton_V3_C_PreConstruct final 
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(W_MainMenu_SubButton_V3_C_PreConstruct) == 0x000001, "Wrong alignment on W_MainMenu_SubButton_V3_C_PreConstruct");
static_assert(sizeof(W_MainMenu_SubButton_V3_C_PreConstruct) == 0x000001, "Wrong size on W_MainMenu_SubButton_V3_C_PreConstruct");
static_assert(offsetof(W_MainMenu_SubButton_V3_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'W_MainMenu_SubButton_V3_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function W_MainMenu_SubButton_V3.W_MainMenu_SubButton_V3_C.SetState
// 0x0060 (0x0060 - 0x0000)
struct W_MainMenu_SubButton_V3_C_SetState final 
{
public:
	bool                                          Hovered;                                           // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Selected;                                          // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_41FA[0x6];                                     // 0x0002(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateColor                            White_90;                                          // 0x0008(0x0028)(Edit, BlueprintVisible)
	struct FSlateColor                            White_40;                                          // 0x0030(0x0028)(Edit, BlueprintVisible)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(W_MainMenu_SubButton_V3_C_SetState) == 0x000008, "Wrong alignment on W_MainMenu_SubButton_V3_C_SetState");
static_assert(sizeof(W_MainMenu_SubButton_V3_C_SetState) == 0x000060, "Wrong size on W_MainMenu_SubButton_V3_C_SetState");
static_assert(offsetof(W_MainMenu_SubButton_V3_C_SetState, Hovered) == 0x000000, "Member 'W_MainMenu_SubButton_V3_C_SetState::Hovered' has a wrong offset!");
static_assert(offsetof(W_MainMenu_SubButton_V3_C_SetState, Selected) == 0x000001, "Member 'W_MainMenu_SubButton_V3_C_SetState::Selected' has a wrong offset!");
static_assert(offsetof(W_MainMenu_SubButton_V3_C_SetState, White_90) == 0x000008, "Member 'W_MainMenu_SubButton_V3_C_SetState::White_90' has a wrong offset!");
static_assert(offsetof(W_MainMenu_SubButton_V3_C_SetState, White_40) == 0x000030, "Member 'W_MainMenu_SubButton_V3_C_SetState::White_40' has a wrong offset!");
static_assert(offsetof(W_MainMenu_SubButton_V3_C_SetState, CallFunc_Not_PreBool_ReturnValue) == 0x000058, "Member 'W_MainMenu_SubButton_V3_C_SetState::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");

}

