#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_Tutorial

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "ReadyOrNot_classes.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_Tutorial.W_Tutorial_C
// 0x0070 (0x0410 - 0x03A0)
class UW_Tutorial_C final  : public UTutorialWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03A0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       AnimReveal;                                        // 0x03A8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UImage*                                 Image_367;                                         // 0x03B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Img_RedLine;                                       // 0x03B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UScaleBox*                              MediaScaleBox;                                     // 0x03C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               MediaSizeBox;                                      // 0x03C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonRichTextBlock*                   Rtxt_Description;                                  // 0x03D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UScaleBox*                              ScaleBox;                                          // 0x03D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       Txt_Title;                                         // 0x03E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           VB_TutContent;                                     // 0x03E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           VB_Tutorial;                                       // 0x03F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_Footer_C*                            W_Footer;                                          // 0x03F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	FMulticastInlineDelegateProperty_             OnTutorialWidgetRemoved;                           // 0x0400(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void OnTutorialWidgetRemoved__DelegateSignature();
	void ExecuteUbergraph_W_Tutorial(int32 EntryPoint, bool Temp_bool_Variable, TDelegate<void()> K2Node_CreateDelegate_OutputDelegate, ESlateVisibility Temp_byte_Variable, ESlateVisibility Temp_byte_Variable_1, class UUMGSequencePlayer* CallFunc_PlayAnimationForward_ReturnValue, class FText CallFunc_GetDescription_ReturnValue, class FText CallFunc_GetTitle_ReturnValue, float CallFunc_SelectFloat_ReturnValue, float CallFunc_GetAnimationCurrentTime_ReturnValue, bool CallFunc_Less_FloatFloat_ReturnValue, bool CallFunc_IsAnimationPlaying_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, class UUMGSequencePlayer* CallFunc_PlayAnimationReverse_ReturnValue, bool CallFunc_IsAnimationPlayingForward_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, float CallFunc_PauseAnimation_ReturnValue, bool CallFunc_IsVisible_ReturnValue, class UUMGSequencePlayer* CallFunc_PlayAnimation_ReturnValue, ESlateVisibility K2Node_Select_Default);
	void BndEvt__W_Tutorial_W_Footer_K2Node_ComponentBoundEvent_1_OnDismissInputAction__DelegateSignature();
	void Construct();
	void RefreshWidget();
	void Hide_Widget_End();
	void ShowMainWidget();
	void HideMainWidget();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"W_Tutorial_C">();
	}
	static class UW_Tutorial_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_Tutorial_C>();
	}
};
static_assert(alignof(UW_Tutorial_C) == 0x000008, "Wrong alignment on UW_Tutorial_C");
static_assert(sizeof(UW_Tutorial_C) == 0x000410, "Wrong size on UW_Tutorial_C");
static_assert(offsetof(UW_Tutorial_C, UberGraphFrame) == 0x0003A0, "Member 'UW_Tutorial_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UW_Tutorial_C, AnimReveal) == 0x0003A8, "Member 'UW_Tutorial_C::AnimReveal' has a wrong offset!");
static_assert(offsetof(UW_Tutorial_C, Image_367) == 0x0003B0, "Member 'UW_Tutorial_C::Image_367' has a wrong offset!");
static_assert(offsetof(UW_Tutorial_C, Img_RedLine) == 0x0003B8, "Member 'UW_Tutorial_C::Img_RedLine' has a wrong offset!");
static_assert(offsetof(UW_Tutorial_C, MediaScaleBox) == 0x0003C0, "Member 'UW_Tutorial_C::MediaScaleBox' has a wrong offset!");
static_assert(offsetof(UW_Tutorial_C, MediaSizeBox) == 0x0003C8, "Member 'UW_Tutorial_C::MediaSizeBox' has a wrong offset!");
static_assert(offsetof(UW_Tutorial_C, Rtxt_Description) == 0x0003D0, "Member 'UW_Tutorial_C::Rtxt_Description' has a wrong offset!");
static_assert(offsetof(UW_Tutorial_C, ScaleBox) == 0x0003D8, "Member 'UW_Tutorial_C::ScaleBox' has a wrong offset!");
static_assert(offsetof(UW_Tutorial_C, Txt_Title) == 0x0003E0, "Member 'UW_Tutorial_C::Txt_Title' has a wrong offset!");
static_assert(offsetof(UW_Tutorial_C, VB_TutContent) == 0x0003E8, "Member 'UW_Tutorial_C::VB_TutContent' has a wrong offset!");
static_assert(offsetof(UW_Tutorial_C, VB_Tutorial) == 0x0003F0, "Member 'UW_Tutorial_C::VB_Tutorial' has a wrong offset!");
static_assert(offsetof(UW_Tutorial_C, W_Footer) == 0x0003F8, "Member 'UW_Tutorial_C::W_Footer' has a wrong offset!");
static_assert(offsetof(UW_Tutorial_C, OnTutorialWidgetRemoved) == 0x000400, "Member 'UW_Tutorial_C::OnTutorialWidgetRemoved' has a wrong offset!");

}

